### ISSUE TITLE
Ask about pre-trained models

### ISSUE THREAD

**Issue by kimnamu** [htdt/hyp_metric#5]
Thank you for sharing a great paper and source!
So I hope to apply my task using these models.
Can I request the pre-trained model such as hyp-DINO, Hyp-ViT?
Thank you.

**Comment by htdt** [comment]
Thanks for your interest in our method! Unfortunately, I didn't store checkpoints with models. There are two reasons for this: the training does not require a lot of time, e.g. training and validating Hyp-ViT on CUB on one A100 GPU took 14 minutes; the results were reproducible, the difference between the runs was insignificant.

**Comment by kimnamu** [comment]
Thank you for your kind reply. I understand it well enough, and I will train and use it.
