### ISSUE TITLE
Assertion error from `train.py`

### ISSUE THREAD

**Issue by letme-hj** [htdt/hyp_metric#8]
Hi, thank you for your work and kindly sharing the code!

While I was trying to run your code on InShop dataset, I faced an assertion error from L143 in train.py.
https://github.com/htdt/hyp_metric/blob/c89de0490691bacbd7332171c5455651fe49f25e/train.py#L143

I did not deeply go over the code yet, but I looked at the dataset class and found nothing weird.
I wonder if you have anything that comes to your mind regarding this error.
Below is what `y` looks like, and it seems like there are some rows that are not equal. The paired values are quite close though.
<img width="140" alt="스크린샷 2023-10-24 오후 1 33 46" src="https://github.com/htdt/hyp_metric/assets/63252804/50f1bdb8-a1db-4e63-a177-fb2c76f59599">

Thanks!

**Comment by htdt** [comment]
Two columns must be equal, we use the same labels for positives. I recommend to validate if the dataset is copied correctly. After that, I recommend to use the original code with parameters from the paper.
